### ISSUE TITLE
LFO phase set

### ISSUE THREAD

**Issue by libesz** [JordanAceto/synth-utils-rs#3]
I would like to ask if there would be a good way to set the LFO phase (like reset to a certain point). Would be useful for when LFO is started on note triggers, but from a user-defined phase of a certain waveshape.

**Comment by JordanAceto** [comment]
This does sound like a useful addition. I have not thought too much about it, but I think it will be relatively easy to add. Maybe it's as simple as including a phase offset parameter which is added to the raw accumulator before the waveshaping happens? I'm sure there is lots of prior art to copy here.

I probably won't work on this very soon, but I might eventually get to it. If you happen to implement this I'd be happy to merge it in.

**Comment by libesz** [comment]
I figured out an easy-looking solution for this. Hope that make sense 😄
